default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-minister-cocktail_development

test:
  <<: *default
  database: rails-minister-cocktail_test
